In [6]:
import numpy as np
import pandas as pd
import os, sys
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [3]:
df=pd.read_csv('C:/Users/devil/Desktop/parkinsons.data')
df.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [4]:
df.describe()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
count   195.000000    195.000000    195.000000      195.000000   
mean    154.228641    197.104918    116.324631        0.006220   
std      41.390065     91.491548     43.521413        0.004848   
min      88.333000    102.145000     65.476000        0.001680   
25%     117.572000    134.862500     84.291000        0.003460   
50%     148.790000    175.829000    104.315000        0.004940   
75%     182.769000    224.205500    140.018500        0.007365   
max     260.105000    592.030000    239.170000        0.033160   

       MDVP:Jitter(Abs)    MDVP:RAP    MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
count        195.000000  195.000000  195.000000  195.000000    195.000000   
mean           0.000044    0.003306    0.003446    0.009920      0.029709   
std            0.000035    0.002968    0.002759    0.008903      0.018857   
min            0.000007    0.000680    0.000920    0.002040      0.009540   
25%            0.000020    0.001660    0.001860    0.004985      0.016505   
50%            0.000030    0.002500    0.002690    0.007490      0.022970   
75%            0.000060    0.003835    0.003955    0.011505      0.037885   
max            0.000260    0.021440    0.019580    0.064330      0.119080   

       MDVP:Shimmer(dB)  ...  Shimmer:DDA         NHR         HNR      status  \
count        195.000000  ...   195.000000  195.000000  195.000000  195.000000   
mean           0.282251  ...     0.046993    0.024847   21.885974    0.753846   
std            0.194877  ...     0.030459    0.040418    4.425764    0.431878   
min            0.085000  ...     0.013640    0.000650    8.441000    0.000000   
25%            0.148500  ...     0.024735    0.005925   19.198000    1.000000   
50%            0.221000  ...     0.038360    0.011660   22.085000    1.000000   
75%            0.350000  ...     0.060795    0.025640   25.075500    1.000000   
max            1.302000  ...     0.169420    0.314820   33.047000    1.000000   

             RPDE         DFA     spread1     spread2          D2         PPE  
count  195.000000  195.000000  195.000000  195.000000  195.000000  195.000000  
mean     0.498536    0.718099   -5.684397    0.226510    2.381826    0.206552  
std      0.103942    0.055336    1.090208    0.083406    0.382799    0.090119  
min      0.256570    0.574282   -7.964984    0.006274    1.423287    0.044539  
25%      0.421306    0.674758   -6.450096    0.174351    2.099125    0.137451  
50%      0.495954    0.722254   -5.720868    0.218885    2.361532    0.194052  
75%      0.587562    0.761881   -5.046192    0.279234    2.636456    0.252980  
max      0.685151    0.825288   -2.434031    0.450493    3.671155    0.527367  

[8 rows x 23 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [27]:
np.percentile(df.spread1,[99])

array([-8.77200486])

In [13]:
np.percentile(df.spread1,[99])[0]

-2.9240016199999994

In [14]:
uv=np.percentile(df.spread1,[99])[0]

In [17]:
df[(df.spread1>uv)]

Empty DataFrame
Columns: [name, MDVP:Fo(Hz), MDVP:Fhi(Hz), MDVP:Flo(Hz), MDVP:Jitter(%), MDVP:Jitter(Abs), MDVP:RAP, MDVP:PPQ, Jitter:DDP, MDVP:Shimmer, MDVP:Shimmer(dB), Shimmer:APQ3, Shimmer:APQ5, MDVP:APQ, Shimmer:DDA, NHR, HNR, status, RPDE, DFA, spread1, spread2, D2, PPE]
Index: []

[0 rows x 24 columns]

In [16]:
df.spread1[(df.spread1>3*uv)] =3*uv

<ipython-input-16-eb367d80fa41>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.spread1[(df.spread1>3*uv)] =3*uv


In [38]:
df.columns = df.columns.str.strip()
print (df.columns[1])

MDVP_Fo


In [37]:
df = df.rename(columns={'MDVP_Fo(Hz)': 'MDVP_Fo'})

In [39]:
np.percentile(df.MDVP_Fo,[99])

array([245.9267])

In [40]:
np.percentile(df.MDVP_Fo,[99])[0]

245.9267

In [45]:
uv2=np.percentile(df.MDVP_Fo,[99])[0]

In [48]:
df[(df.MDVP_Fo>uv2)]

name  MDVP_Fo  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
47   phon_R01_S10_6  252.455       261.487       182.786         0.00185   
167  phon_R01_S42_3  260.105       264.919       237.303         0.00339   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
47           0.000007   0.00092   0.00113     0.00276       0.01152  ...   
167          0.000010   0.00205   0.00186     0.00616       0.02030  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
47       0.01841  0.00432  26.805       0  0.610367  0.635204 -8.772005   
167      0.03557  0.00910  21.083       0  0.440988  0.628058 -8.772005   

      spread2        D2       PPE  
47   0.200873  2.028612  0.086398  
167  0.160414  1.881767  0.075587  

[2 rows x 24 columns]

In [47]:
df.MDVP_Fo[(df.MDVP_Fo>3*uv2)] =3*uv2

<ipython-input-47-54fbde9e2f6d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.MDVP_Fo[(df.MDVP_Fo>3*uv2)] =3*uv2


In [49]:
df = df.rename(columns={'MDVP:Fhi(Hz)': 'MDVP_Fhi'})

In [51]:
np.percentile(df.MDVP_Fhi,[99])

array([586.68406])

In [52]:
np.percentile(df.MDVP_Fhi,[99])[0]

586.6840599999999

In [53]:
uv3=np.percentile(df.MDVP_Fhi,[99])[0]

In [67]:
df[(df.MDVP_Fhi>uv3)]

name  MDVP_Fo  MDVP_Fhi  MDVP_Flo  MDVP:Jitter(%)  \
73   phon_R01_S19_2  112.014   588.518   107.024         0.00533   
186  phon_R01_S49_4  116.556   592.030    86.228         0.00496   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
73            0.00005   0.00268   0.00329     0.00805       0.02448  ...   
186           0.00004   0.00254   0.00263     0.00762       0.01660  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
73        0.0412  0.00623  24.178       1  0.509127  0.789532 -8.772005   
186       0.0246  0.01397  23.958       0  0.566424  0.667654 -8.772005   

      spread2        D2       PPE  
73   0.306636  1.928708  0.225461  
186  0.153310  2.161936  0.120605  

[2 rows x 24 columns]

In [66]:
df.MDVP_Fhi[(df.MDVP_Fhi>3*uv3)] =3*uv3

<ipython-input-66-0dd296481763>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.MDVP_Fhi[(df.MDVP_Fhi>3*uv3)] =3*uv3


In [60]:
df = df.rename(columns={'MDVP:Flo(Hz)': 'MDVP_Flo'})

In [61]:
np.percentile(df.MDVP_Flo,[99])

array([232.7722])

In [70]:
uv4=np.percentile(df.MDVP_Flo,[99])[0]

In [72]:
df.MDVP_Flo[(df.MDVP_Flo>3*uv4)] =3*uv4

<ipython-input-72-9e2727848b1a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.MDVP_Flo[(df.MDVP_Flo>3*uv4)] =3*uv4


In [73]:
df[(df.MDVP_Flo>uv4)]

name  MDVP_Fo  MDVP_Fhi  MDVP_Flo  MDVP:Jitter(%)  \
167  phon_R01_S42_3  260.105   264.919   237.303         0.00339   
170  phon_R01_S42_6  244.990   272.210   239.170         0.00451   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
167           0.00001   0.00205   0.00186     0.00616       0.02030  ...   
170           0.00002   0.00279   0.00237     0.00837       0.01897  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
167      0.03557  0.00910  21.083       0  0.440988  0.628058 -8.772005   
170      0.03253  0.01049  21.528       0  0.522812  0.646818 -8.772005   

      spread2        D2       PPE  
167  0.160414  1.881767  0.075587  
170  0.171088  2.095237  0.096220  

[2 rows x 24 columns]

In [64]:
df.head()

name  MDVP_Fo  MDVP_Fhi  MDVP_Flo  MDVP:Jitter(%)  \
0  phon_R01_S01_1  119.992   157.302    74.997         0.00784   
1  phon_R01_S01_2  122.400   148.650   113.819         0.00968   
2  phon_R01_S01_3  116.682   131.111   111.555         0.01050   
3  phon_R01_S01_4  116.676   137.871   111.366         0.00997   
4  phon_R01_S01_5  116.014   141.781   110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -8.772005   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -8.772005   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -8.772005   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -8.772005   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -8.772005   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [65]:
df.describe()

MDVP_Fo    MDVP_Fhi    MDVP_Flo  MDVP:Jitter(%)  MDVP:Jitter(Abs)  \
count  195.000000  195.000000  195.000000      195.000000        195.000000   
mean   154.228641  197.104918  116.324631        0.006220          0.000044   
std     41.390065   91.491548   43.521413        0.004848          0.000035   
min     88.333000  102.145000   65.476000        0.001680          0.000007   
25%    117.572000  134.862500   84.291000        0.003460          0.000020   
50%    148.790000  175.829000  104.315000        0.004940          0.000030   
75%    182.769000  224.205500  140.018500        0.007365          0.000060   
max    260.105000  592.030000  239.170000        0.033160          0.000260   

         MDVP:RAP    MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  MDVP:Shimmer(dB)  \
count  195.000000  195.000000  195.000000    195.000000        195.000000   
mean     0.003306    0.003446    0.009920      0.029709          0.282251   
std      0.002968    0.002759    0.008903      0.018857          0.194877   
min      0.000680    0.000920    0.002040      0.009540          0.085000   
25%      0.001660    0.001860    0.004985      0.016505          0.148500   
50%      0.002500    0.002690    0.007490      0.022970          0.221000   
75%      0.003835    0.003955    0.011505      0.037885          0.350000   
max      0.021440    0.019580    0.064330      0.119080          1.302000   

       ...  Shimmer:DDA         NHR         HNR      status        RPDE  \
count  ...   195.000000  195.000000  195.000000  195.000000  195.000000   
mean   ...     0.046993    0.024847   21.885974    0.753846    0.498536   
std    ...     0.030459    0.040418    4.425764    0.431878    0.103942   
min    ...     0.013640    0.000650    8.441000    0.000000    0.256570   
25%    ...     0.024735    0.005925   19.198000    1.000000    0.421306   
50%    ...     0.038360    0.011660   22.085000    1.000000    0.495954   
75%    ...     0.060795    0.025640   25.075500    1.000000    0.587562   
max    ...     0.169420    0.314820   33.047000    1.000000    0.685151   

              DFA       spread1     spread2          D2         PPE  
count  195.000000  1.950000e+02  195.000000  195.000000  195.000000  
mean     0.718099 -8.772005e+00    0.226510    2.381826    0.206552  
std      0.055336  2.137115e-14    0.083406    0.382799    0.090119  
min      0.574282 -8.772005e+00    0.006274    1.423287    0.044539  
25%      0.674758 -8.772005e+00    0.174351    2.099125    0.137451  
50%      0.722254 -8.772005e+00    0.218885    2.361532    0.194052  
75%      0.761881 -8.772005e+00    0.279234    2.636456    0.252980  
max      0.825288 -8.772005e+00    0.450493    3.671155    0.527367  

[8 rows x 23 columns]